title: Jack Gerrits
description: >
  Personal Website

baseurl: ""                     # the subpath of your site, e.g. /blog
url: https://jackgerrits.com    # with the https protocol
enforce_ssl: jackgerrits.com    # without any protocol

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project     # Sets the default layout of pages in projects collection to project

collections:
  projects:
    output: true            # Sets pages in the projects collection to output html pages

# Build settings
markdown: kramdown
